version: '3.8'
services:
  backend:
    build: .
    container_name: uth_club_backend
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
